/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface appModelSchema {
  app_id?: number;
  branch: string;
  category_id?: number;
  compose_path: string;
  created_by?: string;
  modified_by?: string;
  name: string;
  repo: string;
  root_path: string;
  status?: number;
  webhook_url: string;
}

export interface categoryModelSchema {
  category_id?: number;
  created_by?: string;
  modified_by?: string;
  name: string;
  status?: number;
}

export interface envModelSchema {
  app_id?: number;
  created_by?: string;
  env_id?: number;
  modified_by?: string;
  prop_key: string;
  prop_value: string;
  status?: number;
}

export interface permissionModelSchema {
  created_by?: string;
  description: string;
  modified_by?: string;
  permission_id?: number;
  ref_name: string;
  scope: string;
  sequence?: number;
  status?: number;
}

export interface roleModelSchema {
  created_by?: string;
  description: string;
  modified_by?: string;
  ref_name: string;
  role_id?: number;
  status?: number;
}

export interface rolePermissionModelSchema {
  created_by?: string;
  description: string;
  modified_by?: string;
  permission_id?: number;
  ref_name: string;
  scope: string;
  sequence?: number;
  status?: number;
}

export interface userModelSchema {
  created_by?: string;
  email: string;
  modified_by?: string;
  name: string;
  password: string;
  role_id: string;
  status?: number;
  user_id?: number;
  username: string;
}
